# Generated by Django 3.2.16 on 2022-12-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
