# Generated by Django 3.2.16 on 2022-12-02 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/users')),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('middleName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('contactPhone', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('companySite', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('timeZone', models.CharField(blank=True, max_length=50, null=True)),
                ('communication', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=200, null=True)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, default='United States', max_length=50, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=150, null=True)),
                ('userType', models.CharField(blank=True, choices=[('superadmin', 'superadmin'), ('admin', 'admin'), ('user', 'user')], max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validityFrom', models.CharField(blank=True, max_length=50, null=True)),
                ('validityTo', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_expire', models.BooleanField(blank=True, default=False, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('access_token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('device_info', models.CharField(blank=True, max_length=250, null=True)),
                ('device_id', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
